### ISSUE TITLE
Crash when running in background

### ISSUE THREAD

**Issue by JohnsonRan** [lz233/Tarnhelm#12]
https://nekobin.com/vipipedaca

**Comment by lz233** [comment]
@qqlittleice233

**Comment by lz233** [comment]
cloud you catch some logs?

**Comment by JohnsonRan** [comment]
[LSPosed_2022-08-18T14_23_10.769.zip](https://github.com/lz233/Tarnhelm/files/9368134/LSPosed_2022-08-18T14_23_10.769.zip)
Here's LSPosed log if needed

**Comment by lz233** [comment]
```
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=cn.ac.lz233.tarnhelm.bridge pkg=cn.ac.lz233.tarnhelm }: app is in background uid UidRecord{28415e3 u0a73 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1525)
        at android.app.ContextImpl.startService(ContextImpl.java:1481)
        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
        at cn.ac.lz233.tarnhelm.App.onCreate(App.kt:54)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5781)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6548) 
        at java.lang.reflect.Method.invoke(Native Method)
```

**Comment by JohnsonRan** [comment]
> cloud you catch some logs?

Eh,i think i already attached them?

**Comment by lz233** [comment]
> > cloud you catch some logs?
> 
> Eh,i think i already attached them?

yep

**Comment by JohnsonRan** [comment]
https://nekobin.com/pojevoyamo
Crash when using Tarnhelm Copy🤣

**Comment by qqlittleice233** [comment]
> 
[app-debug.zip](https://github.com/lz233/Tarnhelm/files/9374106/app-debug.zip)
try this

**Comment by JohnsonRan** [comment]
> @JohnsonRan [app-debug.zip](https://github.com/lz233/Tarnhelm/files/9374106/app-debug.zip) try this

Same

**Comment by qqlittleice233** [comment]
> > @JohnsonRan [app-debug.zip](https://github.com/lz233/Tarnhelm/files/9374106/app-debug.zip) try this
> 
> Same

log pls

**Comment by JohnsonRan** [comment]
> > > @JohnsonRan [app-debug.zip](https://github.com/lz233/Tarnhelm/files/9374106/app-debug.zip) try this
> > 
> > 
> > Same
> 
> log pls

https://nekobin.com/mitigusoqi

**Comment by lz233** [comment]
> https://nekobin.com/pojevoyamo

`Caused by: java.lang.Throwable: non-standard array`

So this one is in charge of you. Make sure `regex` and `replacement` have the same number of lines.

**Comment by JohnsonRan** [comment]
> > https://nekobin.com/pojevoyamo
> 
> `Caused by: java.lang.Throwable: non-standard array`
> 
> So this one is in charge of you. Make sure `regex` and `replacement` have the same number of lines.

![Screenshot_20220819-171815_Tarnhelm~3](https://user-images.githubusercontent.com/89735151/185587814-be24c142-52d2-4909-869d-db8b139b28c3.png)
Hmmm..
It works if i copy paste other rules then replace domains

**Comment by JohnsonRan** [comment]
> > https://nekobin.com/pojevoyamo
> 
> `Caused by: java.lang.Throwable: non-standard array`
> 
> So this one is in charge of you. Make sure `regex` and `replacement` have the same number of lines.

Yea,i just figured out
