### ISSUE TITLE
Repeated crashes when upgrading to Android 14 QPR2

### ISSUE THREAD

**Issue by CoelacanthusHex** [lz233/Tarnhelm#52]
Backtrace:
```
java.lang.RuntimeException: Unable to create application cn.ac.lz233.tarnhelm.App: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { act=cn.ac.lz233.tarnhelm.bridge pkg=cn.ac.lz233.tarnhelm }: app is in background uid UidRecord{7a9a587 u0a483 CEM  idle change:idle|cached|procstate procs:0 seq(2460,2346)} caps=------
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7312)
 at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loopOnce(Looper.java:232)
 at android.os.Looper.loop(Looper.java:317)
 at android.app.ActivityThread.main(ActivityThread.java:8501)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { act=cn.ac.lz233.tarnhelm.bridge pkg=cn.ac.lz233.tarnhelm }: app is in background uid UidRecord{7a9a587 u0a483 CEM  idle change:idle|cached|procstate procs:0 seq(2460,2346)} caps=------
 at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1946)
 at android.app.ContextImpl.startService(ContextImpl.java:1901)
 at android.content.ContextWrapper.startService(ContextWrapper.java:826)
 at cn.ac.lz233.tarnhelm.App.onCreate(Unknown Source:1041)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1379)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7307)
 ... 9 more
```
There seem to be some new background limitations, but I don't even enable Background Monitoring...

**Comment by CoelacanthusHex** [comment]
It seems disappear for 20 days. Close.
